"""
config/settings.py
------------------
Centralized configuration using Pydantic Settings.

Improvements over v1:
  - Fixed RelaySettings env_prefix (was "nexus-relay-", hyphens not valid)
  - TLS cert paths now match what crypto.py actually generates
  - YAML defaults loader: call load_yaml_defaults() to merge defaults.yaml
    before instantiating settings (optional but recommended)
  - Added `relay_url` helper property on NexusSettings
  - Added `api_url` helper property
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Sub-settings classes
# ---------------------------------------------------------------------------

class TLSSettings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="NEXUS_TLS_")

    # These match the filenames generated by utils/crypto.py
    cert_file: Path = BASE_DIR / "certs" / "nexus-relay-server.crt"
    key_file: Path = BASE_DIR / "certs" / "nexus-relay-server.key"
    ca_file: Path = BASE_DIR / "certs" / "ca.crt"
    require_client_cert: bool = True
    min_tls_version: str = "TLSv1.3"


class RelaySettings(BaseSettings):
    # FIXED: env_prefix must use underscores (hyphens are invalid)
    model_config = SettingsConfigDict(env_prefix="NEXUS_RELAY_")

    host: str = "0.0.0.0"
    port: int = 7000
    ws_path: str = "/ws"
    max_connections: int = 10_000
    heartbeat_interval: int = 30
    session_timeout: int = 3600
    max_payload_bytes: int = 10 * 1024 * 1024
    plain_tunnel_port: int = 0
    # ↑ 0 = disabled (default). When set, RelayServer.start() binds a SECOND,
    # loopback-only (127.0.0.1), NON-TLS listener on this port, used
    # exclusively as the target of a reverse tunnel like pinggy.io's default
    # HTTP-tunnel mode — which terminates TLS itself and forwards plaintext
    # to whatever it's pointed at. Pointing a TLS-terminating tunnel at the
    # relay's normal TLS listener double-wraps the handshake and breaks the
    # connection; this gives the tunnel a plaintext target to forward to
    # instead, without touching the existing 0.0.0.0 TLS listener used by
    # direct LAN/WAN connections. See setup_and_launch.py's
    # auto_start_public_tunnel() for the client side of this.
    punch_port: int = 0
    # ↑ 0 = reuse `port`'s number for UDP too (TCP and UDP port namespaces
    # are independent, so this never collides with the main TLS listener).
    # RelayServer.start() binds a UDP socket here for transport/hole_punch.py's
    # PunchRendezvousServer — a minimal STUN-lite reflector agents use to
    # learn their own observed public UDP endpoint (Phase 1 of P2P). See
    # transport/hole_punch.py's module docstring for the full picture,
    # including why this only benefits Python-side agents today, not the
    # browser controller.


class AuthSettings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="NEXUS_AUTH_")

    secret_key: str = Field(default="CHANGE_ME_IN_PRODUCTION_32BYTES!!")
    algorithm: str = "HS256"
    access_token_expire_minutes: int = 60
    refresh_token_expire_days: int = 30
    mfa_enabled: bool = True
    max_login_attempts: int = 5
    lockout_minutes: int = 15
    allowed_origins: List[str] = ["*"]


class DatabaseSettings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="NEXUS_DB_")

    url: str = f"sqlite+aiosqlite:///{BASE_DIR}/data/nexus.db"
    echo_sql: bool = False
    pool_size: int = 10
    max_overflow: int = 20


class AgentSettings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="NEXUS_AGENT_")

    screen_fps: int = 15
    screen_quality: int = 75
    screen_scale: float = 1.0
    clipboard_enabled: bool = True
    file_transfer_enabled: bool = True
    terminal_enabled: bool = True
    max_transfer_mb: int = 500
    reconnect_delay: int = 5
    reconnect_max_retries: int = 10


class LogSettings(BaseSettings):
    model_config = SettingsConfigDict(env_prefix="NEXUS_LOG_")

    level: str = "INFO"
    format: str = "json"
    file: Optional[Path] = BASE_DIR / "logs" / "nexus.log"
    max_bytes: int = 10 * 1024 * 1024
    backup_count: int = 5
    audit_file: Optional[Path] = BASE_DIR / "logs" / "audit.log"


# ---------------------------------------------------------------------------
# Root settings
# ---------------------------------------------------------------------------

class NexusSettings(BaseSettings):
    model_config = SettingsConfigDict(
        env_prefix="NEXUS_",
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    app_name: str = "NEXUS Remote Access"
    version: str = "1.0.0"
    debug: bool = False
    environment: str = "production"

    tls: TLSSettings = Field(default_factory=TLSSettings)
    relay: RelaySettings = Field(default_factory=RelaySettings)
    auth: AuthSettings = Field(default_factory=AuthSettings)
    database: DatabaseSettings = Field(default_factory=DatabaseSettings)
    agent: AgentSettings = Field(default_factory=AgentSettings)
    log: LogSettings = Field(default_factory=LogSettings)

    @field_validator("environment")
    @classmethod
    def validate_env(cls, v: str) -> str:
        allowed = {"development", "staging", "production"}
        if v not in allowed:
            raise ValueError(f"environment must be one of {allowed}")
        return v

    # ------------------------------------------------------------------
    # Convenience helpers
    # ------------------------------------------------------------------

    @property
    def relay_url(self) -> str:
        """WebSocket URL for the relay (wss for TLS, ws for dev)."""
        scheme = "wss" if self.tls.cert_file.exists() else "ws"
        return f"{scheme}://{self.relay.host}:{self.relay.port}{self.relay.ws_path}"

    @property
    def api_url(self) -> str:
        """HTTP base URL for the dashboard API."""
        scheme = "https" if self.tls.cert_file.exists() else "http"
        return f"{scheme}://localhost:8080"

    # ------------------------------------------------------------------
    # Runtime setup
    # ------------------------------------------------------------------

    def ensure_dirs(self) -> None:
        """Create required runtime directories if they don't exist."""
        for d in [
            BASE_DIR / "certs",
            BASE_DIR / "data",
            BASE_DIR / "logs",
            BASE_DIR / "recordings",
        ]:
            d.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Optional: load defaults.yaml before instantiating settings
# ---------------------------------------------------------------------------

def load_yaml_defaults(yaml_path: Path | None = None) -> None:
    """
    Pre-populate os.environ with values from defaults.yaml so that
    Pydantic Settings can pick them up. Only sets keys that are NOT
    already set in the environment (env vars always win).

    Call this BEFORE instantiating NexusSettings() if you want YAML
    defaults to be respected.
    """
    import os

    try:
        import yaml
    except ImportError:
        return  # PyYAML not installed — skip silently

    path = yaml_path or (BASE_DIR / "config" / "defaults.yaml")
    if not path.exists():
        return

    with open(path) as f:
        data = yaml.safe_load(f) or {}

    def _flatten(d: dict, prefix: str = "") -> dict:
        out = {}
        for k, v in d.items():
            key = f"{prefix}_{k}".upper() if prefix else k.upper()
            if isinstance(v, dict):
                out.update(_flatten(v, key))
            elif isinstance(v, list):
                out[key] = ",".join(str(x) for x in v)
            else:
                out[key] = str(v)
        return out

    flat = _flatten(data, prefix="NEXUS")
    for k, v in flat.items():
        if k not in os.environ:
            os.environ[k] = v


# Singleton
settings = NexusSettings()
